RIPTIDE_DOCKER_LABEL_IS_RIPTIDE = 'riptide'
RIPTIDE_DOCKER_LABEL_SERVICE = "riptide_service"
RIPTIDE_DOCKER_LABEL_PROJECT = "riptide_project"
RIPTIDE_DOCKER_LABEL_MAIN = "riptide_main"
RIPTIDE_DOCKER_LABEL_HTTP_PORT = "riptide_port"